const groups = [
  {name:'Foundations',items:[['Overview','overview'],['Color','foundations/color'],['Typography','foundations/typography'],['Spacing & grid','foundations/layout'],['Shape & elevation','foundations/shape'],['Icons & imagery','foundations/media'],['Motion','foundations/motion']]},
  {name:'Actions',items:[['Buttons','actions/buttons'],['Icon buttons','actions/icon-buttons'],['Links','actions/links']]},
  {name:'Forms',items:[['Inputs','forms/inputs'],['Textarea','forms/textarea'],['Select','forms/select'],['Checkbox','forms/checkbox'],['Radio','forms/radio'],['Switch','forms/switch'],['Validation','forms/validation'],['Search','forms/search'],['Availability search','forms/availability']]},
  {name:'Feedback',items:[['Alerts','feedback/alerts'],['Modal','feedback/modal'],['Loading','feedback/loading'],['Empty states','feedback/empty'],['Progress & toast','feedback/progress']]},
  {name:'Navigation',items:[['Header','navigation/header'],['Breadcrumbs','navigation/breadcrumbs'],['Tabs','navigation/tabs'],['Accordion','navigation/accordion'],['Pagination','navigation/pagination'],['Footer','navigation/footer']]},
  {name:'Content',items:[['Cards','content/cards'],['Service tiles','content/service-tiles'],['Metric strip','content/metrics'],['Data table','content/table'],['Media gallery','content/gallery'],['Rich text','content/rich-text']]},
  {name:'Patterns',items:[['Booking flow','patterns/booking'],['Consultation','patterns/consultation'],['Search results','patterns/results'],['Modal pattern','patterns/modal']]},
  {name:'Blocks',items:[['Hero','blocks/hero'],['Task wall','blocks/task-wall'],['Card collection','blocks/card-collection'],['Promotional block','blocks/promo'],['Information CTA','blocks/info-cta'],['Quick links','blocks/quick-links'],['Article layout','blocks/article'],['Related content','blocks/related'],['Share group','blocks/share']]},
  {name:'Complete pages',items:[['Retreat home','examples/home'],['Room collection','examples/rooms'],['Program detail','examples/program']]}
];

const meta = {
  'actions/buttons':['Button','Triggers a primary or supporting action. Use one primary action per decision area.','btn, btn.secondary, btn.ghost','--accent, --accent-contrast, --control-md'],
  'actions/icon-buttons':['Icon button','Provides a compact action when the symbol is familiar.','icon-btn, icon-btn.square','--control-md, --radius-pill, --border'],
  'actions/links':['Link','Moves the user to another destination or document position.','text-link, nav-link','--accent, --focus'],
  'forms/inputs':['Text input','Collects a short, free-form value.','field, input, field-note','--surface, --border, --focus'],
  'forms/textarea':['Textarea','Collects multi-line notes or requests.','field, textarea','--surface, --border, --radius-sm'],
  'forms/select':['Select','Lets users choose one option from a compact native list.','field, select','--surface, --border, --muted'],
  'forms/checkbox':['Checkbox','Supports independent, optional selections.','choice','--accent, --focus'],
  'forms/radio':['Radio group','Selects exactly one mutually exclusive option.','choice','--accent, --focus'],
  'forms/switch':['Switch','Changes a setting immediately.','choice, switch','--accent, --border'],
  'forms/validation':['Validation','Communicates field-level errors and success without color alone.','field.error, field.success, field-note','--danger, --success'],
  'forms/search':['Search','Finds services or content within a known collection.','field, input, btn','--surface, --border, --accent'],
  'forms/availability':['Availability search','Combines dates and party size into the primary reservation action.','booking-bar, input, btn','--pine-900, --accent'],
  'feedback/alerts':['Alert','Surfaces important contextual status without interrupting the task.','alert, alert.success, alert.warning, alert.error','--info, --success, --warning, --danger'],
  'feedback/modal':['Modal','Requests focused input while preserving page context.','modal-backdrop, modal, modal-actions','--surface, --shadow-lg'],
  'feedback/loading':['Loading','Reserves layout while content is being fetched.','skeleton','--border, --surface'],
  'feedback/empty':['Empty state','Explains why a collection has no results and offers recovery.','empty, empty-icon','--surface-2, --muted'],
  'feedback/progress':['Progress and toast','Shows task completion and transient confirmation.','progress, toast','--accent, --shadow-md'],
  'navigation/header':['Header','Anchors identity, primary navigation and the key booking action.','site-header, site-logo, site-nav','--surface, --border'],
  'navigation/breadcrumbs':['Breadcrumbs','Shows hierarchy on deep content pages.','breadcrumb','--muted, --accent'],
  'navigation/tabs':['Tabs','Switches between peer views without leaving context.','tabs, tab-list, tab, tab-panel','--border, --accent'],
  'navigation/accordion':['Accordion','Progressively reveals dense supporting information.','accordion','--border, --accent'],
  'navigation/pagination':['Pagination','Moves through a long, ordered collection.','pagination','--border, --accent'],
  'navigation/footer':['Footer','Provides stable utility navigation and contact paths.','site-footer','--pine-900, --brand-300'],
  'content/cards':['Card','Groups an image, summary and action into one selectable object.','card, media, card-body','--surface, --border, --shadow-sm'],
  'content/service-tiles':['Service tile','Introduces a destination with strong editorial imagery.','card, media, badge','--surface, --accent'],
  'content/metrics':['Metric strip','Summarizes proof points in a quick scanning row.','metric','--accent, --muted'],
  'content/table':['Data table','Compares structured plan, room or price attributes.','price-table','--border, --accent'],
  'content/gallery':['Media gallery','Presents visual content with a clear active item and controls.','media, icon-btn','--surface, --shadow-sm'],
  'content/rich-text':['Rich text','Formats editorial or clinical information for sustained reading.','prose, quote','--text, --muted, --accent'],
  'patterns/booking':['Booking flow','Moves from search criteria to a reviewable selection.','booking-bar, card, progress','--pine-900, --accent'],
  'patterns/consultation':['Consultation pattern','Pairs compact context with a low-friction contact form.','split, field, btn','--surface-2, --accent'],
  'patterns/results':['Search results','Keeps query, filters, result count and recovery together.','field, card-grid, empty','--surface, --border'],
  'patterns/modal':['Modal pattern','Uses a dialog for short, reversible decisions only.','modal, field, modal-actions','--surface, --shadow-lg'],
  'blocks/hero':['Hero','Establishes destination context and exposes the primary task immediately.','site-hero, site-hero-content','--pine-900, --brand-300'],
  'blocks/task-wall':['Task wall','Turns broad visitor intent into a clear set of next steps.','card-grid, card','--surface, --border'],
  'blocks/card-collection':['Card collection','Groups peer destinations under one scannable heading.','section-heading, card-grid','--surface, --border'],
  'blocks/promo':['Promotional block','Highlights a time-bound offer without hiding conditions.','split, badge, btn','--brand-50, --accent'],
  'blocks/info-cta':['Information CTA','Ends explanatory content with a relevant next action.','split, quote, btn','--surface-2, --accent'],
  'blocks/quick-links':['Quick links','Provides direct access to high-frequency secondary tasks.','stack, btn.secondary','--surface, --border'],
  'blocks/article':['Article layout','Combines metadata, readable measure, sections and related actions.','prose, breadcrumb, share-group','--text, --muted'],
  'blocks/related':['Related content','Offers contextual next reading without repeating the page body.','card-grid, card','--surface, --border'],
  'blocks/share':['Share group','Exposes named share destinations with clear labels.','stack, icon-btn','--border, --focus']
};

const icons = {sun:'☼',moon:'◐',system:'◒',desktop:'▰',tablet:'▯',mobile:'▥',menu:'☰',close:'×',search:'⌕',arrow:'→',check:'✓',info:'i',warn:'!',error:'×',calendar:'□'};
const escapeHTML = (s='') => s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const panel=(title,content)=>`<section class="demo-panel"><h3>${title}</h3>${content}</section>`;
const four=(a,b,c,d)=>`<div class="demo-grid">${a}${b}${c}${d}</div>`;
const image=`<img src="assets/wellness-hero.png" alt="Mountain wellness retreat overlooking a mineral pool">`;
const basicCard=(title='Restorative stay',copy='A calm private room with flexible wellness planning.')=>`<article class="card"><div class="media">${image}</div><div class="card-body"><span class="badge">Available</span><h3>${title}</h3><p>${copy}</p><a href="#/examples/rooms">Explore ${icons.arrow}</a></div></article>`;
const field=(label,placeholder='Enter value',type='text')=>`<div class="field"><label>${label}<input class="input" type="${type}" placeholder="${placeholder}"></label><small class="field-note">Optional supporting guidance.</small></div>`;

function headerDemo(){return `<header class="site-header"><div class="site-logo">LUMEN</div><nav class="site-nav" aria-label="Preview primary"><a href="#">Stays</a><a href="#">Wellness</a><a href="#">Experiences</a><a href="#">About</a></nav><button class="btn sm">Check availability</button></header>`}
function footerDemo(){return `<footer class="site-footer"><div><div class="site-logo">LUMEN</div><p>A restorative mountain retreat shaped around thoughtful care.</p></div><div><h3>Visit</h3><a href="#">Stays</a><br><a href="#">Dining</a></div><div><h3>Wellness</h3><a href="#">Programs</a><br><a href="#">Treatments</a></div><div><h3>Contact</h3><a href="mailto:hello@example.com">hello@example.com</a><br><a href="tel:+10000000000">+1 000 000 0000</a></div></footer>`}
function bookingDemo(){return `<form class="booking-bar" data-demo-form><input class="input" aria-label="Arrival" type="date"><input class="input" aria-label="Departure" type="date"><select class="select" aria-label="Guests"><option>2 guests</option><option>1 guest</option><option>Family</option></select><button class="btn" type="submit">Find a stay</button></form>`}
function alertDemo(cls,title,text){return `<div class="alert ${cls}"><span class="alert-icon" aria-hidden="true">${cls==='success'?icons.check:cls==='warning'?icons.warn:cls==='error'?icons.error:icons.info}</span><div><strong>${title}</strong><div>${text}</div></div></div>`}
function accordionDemo(){return `<div class="accordion"><details open><summary>What is included?</summary><p>Daily breakfast, mineral pool access and a personal arrival consultation.</p></details><details><summary>Can plans be changed?</summary><p>Yes. Flexible reservations can be updated up to 48 hours before arrival.</p></details><details><summary>Is the retreat accessible?</summary><p>Step-free routes and adapted rooms are available on request.</p></details></div>`}
function tabsDemo(){return `<div class="tabs" data-tabs><div class="tab-list" role="tablist"><button class="tab" role="tab" aria-selected="true" data-tab="overview">Overview</button><button class="tab" role="tab" aria-selected="false" data-tab="details">Details</button><button class="tab" role="tab" aria-selected="false" data-tab="policy">Policy</button></div><div class="tab-panel" role="tabpanel">A considered stay with quiet mountain views.</div></div>`}

function demoFor(path){
  switch(path){
    case 'actions/buttons': return four(panel('Hierarchy',`<div class="stack"><button class="btn">Primary</button><button class="btn secondary">Secondary</button><button class="btn ghost">Ghost</button></div>`),panel('Sizes',`<div class="stack"><button class="btn sm">Small</button><button class="btn">Medium</button><button class="btn lg">Large</button></div>`),panel('Intent',`<div class="stack"><button class="btn">Continue</button><button class="btn danger">Remove</button></div>`),panel('States',`<div class="stack"><button class="btn">Default</button><button class="btn" disabled>Disabled</button><button class="btn" aria-busy="true">Loading…</button></div>`));
    case 'actions/icon-buttons': return four(panel('Round',`<button class="icon-btn" aria-label="Search">${icons.search}</button>`),panel('Square',`<button class="icon-btn square" aria-label="Next">${icons.arrow}</button>`),panel('Selected',`<button class="icon-btn" aria-label="Save" aria-pressed="true">${icons.check}</button>`),panel('Disabled',`<button class="icon-btn" aria-label="Unavailable" disabled>${icons.close}</button>`));
    case 'actions/links': return four(panel('Inline',`Learn about our <a href="#">wellness approach</a>.`),panel('Standalone',`<a href="#">View all programs ${icons.arrow}</a>`),panel('Navigation',`<a class="nav-link" href="#"><span class="nav-dot"></span> Program details</a>`),panel('External',`<a href="https://example.com" target="_blank" rel="noreferrer">Visitor information ↗</a>`));
    case 'forms/inputs': return four(panel('Default',field('Full name','Alex Morgan')),panel('With value',`<div class="field"><label>Email<input class="input" value="alex@example.com" type="email"></label></div>`),panel('Disabled',`<div class="field"><label>Member ID<input class="input" value="LM-2048" disabled></label></div>`),panel('Read only',`<div class="field"><label>Country<input class="input" value="United States" readonly></label></div>`));
    case 'forms/textarea': return four(panel('Default',`<div class="field"><label>Notes<textarea class="textarea" placeholder="Tell us what would make your stay comfortable"></textarea></label></div>`),panel('Populated',`<textarea class="textarea">I prefer a quiet room away from the lift.</textarea>`),panel('Required',`<div class="field"><label>Accessibility needs<textarea class="textarea" required></textarea></label><small class="field-note">Required</small></div>`),panel('Disabled',`<textarea class="textarea" disabled>Unavailable</textarea>`));
    case 'forms/select': return four(...['Room type','Program','Party size','Language'].map((x,i)=>panel(x,`<div class="field"><label>${x}<select class="select"><option>${['Any room','Rest & reset','2 guests','English'][i]}</option><option>Alternative option</option></select></label></div>`)));
    case 'forms/checkbox': return four(panel('Unchecked',`<label class="choice"><input type="checkbox"> Airport transfer</label>`),panel('Checked',`<label class="choice"><input type="checkbox" checked> Breakfast included</label>`),panel('Group',`<fieldset><legend class="field-label">Interests</legend><label class="choice"><input type="checkbox"> Hiking</label><label class="choice"><input type="checkbox"> Spa</label></fieldset>`),panel('Disabled',`<label class="choice"><input type="checkbox" disabled> Sold out add-on</label>`));
    case 'forms/radio': return four(...[['Room view','Valley','Forest'],['Payment','Pay now','Pay later'],['Contact','Email','Phone'],['Plan','Flexible','Best rate']].map(x=>panel(x[0],`<fieldset><legend class="field-label">${x[0]}</legend><label class="choice"><input name="${x[0]}" type="radio" checked> ${x[1]}</label><label class="choice"><input name="${x[0]}" type="radio"> ${x[2]}</label></fieldset>`)));
    case 'forms/switch': return four(...[['Email updates',true],['Quiet mode',false],['Reduced motion',false],['Unavailable',false]].map((x,i)=>panel(x[0],`<label class="choice"><input class="switch" type="checkbox" ${x[1]?'checked':''} ${i===3?'disabled':''}> ${x[0]}</label>`)));
    case 'forms/validation': return four(panel('Neutral',field('Name','Your name')),panel('Error',`<div class="field error"><label>Email<input class="input" value="alex@"></label><small class="field-note">Enter a complete email address.</small></div>`),panel('Success',`<div class="field success"><label>Confirmation code<input class="input" value="LUMEN24"></label><small class="field-note">Code applied successfully.</small></div>`),panel('Form error',alertDemo('error','Review 2 fields','Arrival date and email need attention.')));
    case 'forms/search': return four(panel('Compact',`<form class="stack" data-demo-form><input class="input" style="flex:1" type="search" placeholder="Search services" aria-label="Search services"><button class="btn">Search</button></form>`),panel('With query',`<input class="input" type="search" value="massage" aria-label="Search">`),panel('Loading',`<div class="vstack"><input class="input" value="mineral therapy" aria-label="Search"><div class="skeleton"></div></div>`),panel('No result',`<div class="empty"><strong>No matches</strong><div>Try a broader term.</div></div>`));
    case 'forms/availability': return four(panel('Destination hero',bookingDemo()),panel('Compact',`<form class="vstack" data-demo-form>${field('Arrival','','date')}${field('Departure','','date')}<button class="btn">Check dates</button></form>`),panel('Error',alertDemo('error','Dates need attention','Departure must be after arrival.')),panel('Success',alertDemo('success','8 stays available','Flexible rates start from $280.')));
    case 'feedback/alerts': return four(panel('Information',alertDemo('','Before you arrive','Check-in begins at 3:00 PM.')),panel('Success',alertDemo('success','Reservation held','Your room is held for 10 minutes.')),panel('Warning',alertDemo('warning','Limited availability','Only two accessible rooms remain.')),panel('Error',alertDemo('error','Payment not completed','Check the card details and try again.')));
    case 'feedback/modal': return four(panel('Trigger',`<button class="btn" data-open-modal>Open booking note</button>`),panel('Confirmation',`<button class="btn secondary" data-toast="Changes saved">Save changes</button>`),panel('Destructive',`<button class="btn danger" data-toast="Draft removed">Remove draft</button>`),panel('Non-modal alternative',alertDemo('','Prefer inline feedback','Use alerts when no decision is required.')));
    case 'feedback/loading': return four(...['Card','Paragraph','Metrics','Search results'].map((x,i)=>panel(x,`<div class="vstack"><div class="skeleton" style="width:${90-i*12}%"></div><div class="skeleton" style="width:${65+i*4}%"></div><div class="skeleton" style="width:${45+i*8}%"></div></div>`)));
    case 'feedback/empty': return four(...[['No saved stays','Browse rooms'],['No search results','Clear filters'],['No messages','Start a request'],['Offline','Try again']].map(x=>panel(x[0],`<div class="empty"><div class="empty-icon">◇</div><strong>${x[0]}</strong><p>There is nothing to show here yet.</p><button class="btn secondary sm">${x[1]}</button></div>`)));
    case 'feedback/progress': return four(panel('25 percent',`<div class="progress" aria-label="25% complete"><span style="width:25%"></span></div>`),panel('75 percent',`<div class="progress" aria-label="75% complete"><span style="width:75%"></span></div>`),panel('Success toast',`<button class="btn" data-toast="Preference saved">Show toast</button>`),panel('Error toast',`<button class="btn secondary" data-toast="Could not connect. Try again.">Show error</button>`));
    case 'navigation/header': return four(panel('Desktop',headerDemo()),panel('Compact',`<header class="site-header"><div class="site-logo">LUMEN</div><button class="icon-btn" aria-label="Open menu">${icons.menu}</button></header>`),panel('With utility',`<header class="site-header"><div class="site-logo">LUMEN</div><span class="badge">Member stay</span><button class="btn sm">Manage</button></header>`),panel('Transparent',`<header class="site-header" style="background:var(--pine-900);color:#fff"><div class="site-logo">LUMEN</div><button class="btn sm">Reserve</button></header>`));
    case 'navigation/breadcrumbs': return four(...[['Home / Stays / Ridge suite'],['Home / Wellness / Reset'],['Home / Journal / Sleep'],['Back to search results']].map(x=>panel('Example',`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="#">${x[0].split(' / ').join('</a><span>/</span><a href="#">')}</a></nav>`)));
    case 'navigation/tabs': return four(panel('Content',tabsDemo()),panel('Two tabs',`<div class="tabs"><div class="tab-list"><button class="tab" aria-selected="true">Overview</button><button class="tab">Amenities</button></div><div class="tab-panel">Room overview.</div></div>`),panel('Scrollable',`<div class="tab-list">${['All','Rooms','Programs','Treatments','Journal'].map((x,i)=>`<button class="tab" aria-selected="${i===0}">${x}</button>`).join('')}</div>`),panel('Disabled',`<div class="tab-list"><button class="tab" aria-selected="true">Available</button><button class="tab" disabled>Coming soon</button></div>`));
    case 'navigation/accordion': return four(panel('FAQ',accordionDemo()),panel('Single open',`<div class="accordion"><details open><summary>Arrival details</summary><p>Check in from 3:00 PM.</p></details></div>`),panel('Clinical plan',`<div class="accordion"><details><summary>Day one</summary><p>Consultation and assessment.</p></details><details><summary>Day two</summary><p>Movement and recovery.</p></details></div>`),panel('Disabled item',`<div class="accordion"><details><summary>Available section</summary><p>Content</p></details><details style="opacity:.45"><summary>Unavailable section</summary></details></div>`));
    case 'navigation/pagination': return four(...[['1','2','3','Next →'],['←','5','6','7'],['1','…','12','→'],['Previous','1','Next']].map((arr,i)=>panel('Variant',`<nav class="pagination" aria-label="Pagination">${arr.map((x,j)=>`<a href="#" ${j===(i?1:0)?'aria-current="page"':''}>${x}</a>`).join('')}</nav>`)));
    case 'navigation/footer': return four(panel('Full',footerDemo()),panel('Compact',`<footer class="site-footer"><div class="site-logo">LUMEN</div><div>© 2026 Lumen Retreat</div></footer>`),panel('Contact led',`<footer class="site-footer"><div><h3>Plan a stay</h3><a href="mailto:hello@example.com">hello@example.com</a></div><button class="btn">Check dates</button></footer>`),panel('Legal',`<div class="stack"><a href="#">Privacy</a><a href="#">Accessibility</a><a href="#">Terms</a></div>`));
    case 'content/cards': case 'content/service-tiles': return four(panel('Stay',basicCard('Ridge suite','Panoramic outlook, king bed and quiet workspace.')),panel('Program',basicCard('Rest & reset','A guided four-night recovery program.')),panel('Editorial',basicCard('A better evening rhythm','Practical guidance for deeper sleep.')),panel('Unavailable',`<article class="card" style="opacity:.6">${basicCard('Garden room','Currently unavailable').replace('<article class="card">','').replace('</article>','')}</article>`));
    case 'content/metrics': return four(...[['24','private rooms'],['14','guided practices'],['4.9','guest rating'],['92%','return rate']].map(x=>panel(x[1],`<div class="metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`)));
    case 'content/table': return four(panel('Room comparison',`<div style="overflow:auto"><table class="price-table"><thead><tr><th>Room</th><th>Area</th><th>Guests</th><th>From</th></tr></thead><tbody><tr><td>Ridge</td><td>32 m²</td><td>2</td><td>$280</td></tr><tr><td>Valley</td><td>48 m²</td><td>3</td><td>$390</td></tr></tbody></table></div>`),panel('Program schedule',`<table class="price-table"><tr><th>Day</th><th>Focus</th></tr><tr><td>1</td><td>Assessment</td></tr><tr><td>2</td><td>Recovery</td></tr></table>`),panel('Simple facts',`<table class="price-table"><tr><td>Check-in</td><td>3:00 PM</td></tr><tr><td>Check-out</td><td>11:00 AM</td></tr></table>`),panel('Empty',`<div class="empty">No comparable options selected.</div>`));
    case 'content/gallery': return four(panel('Hero image',`<div class="media">${image}</div>`),panel('With controls',`<div class="media">${image}<div class="stack" style="position:absolute;z-index:2;right:1rem;bottom:1rem"><button class="icon-btn" aria-label="Previous">←</button><button class="icon-btn" aria-label="Next">→</button></div></div>`),panel('Thumbnail',`<div class="media" style="aspect-ratio:1">${image}</div>`),panel('Video cover',`<div class="media">${image}<button class="icon-btn" style="position:absolute;z-index:2;inset:50% auto auto 50%;transform:translate(-50%,-50%)" aria-label="Play video">▶</button></div>`));
    case 'content/rich-text': return four(panel('Intro',`<div class="prose"><h2>A gentler daily rhythm</h2><p>Restorative care starts with time, attention and an environment designed to reduce friction.</p></div>`),panel('Quote',`<blockquote class="quote">Wellness works best when it feels sustainable.</blockquote>`),panel('List',`<div class="prose"><h3>Your stay includes</h3><ul><li>Arrival consultation</li><li>Daily breakfast</li><li>Mineral pool access</li></ul></div>`),panel('Metadata',`<div class="eyebrow">Journal · 6 min read</div><h2>Sleep in a new place</h2>`));
    case 'patterns/booking': return four(panel('1. Search',bookingDemo()),panel('2. Select',basicCard('Ridge suite','Flexible · breakfast included')),panel('3. Review',`<div class="vstack"><strong>Ridge suite</strong><span>2 nights · 2 guests</span><div class="progress"><span style="width:75%"></span></div><button class="btn">Continue to details</button></div>`),panel('4. Confirm',alertDemo('success','Stay confirmed','A confirmation has been sent to your email.')));
    case 'patterns/consultation': return four(panel('Form',`<form class="vstack" data-demo-form>${field('Name','Your name')}${field('Email','you@example.com','email')}<button class="btn">Request a call</button></form>`),panel('Phone',`<div class="vstack"><h3>Speak with a host</h3><p>Daily, 8:00 AM–8:00 PM</p><a class="btn secondary" href="tel:+10000000000">Call +1 000 000 0000</a></div>`),panel('Success',alertDemo('success','Request received','A host will reply within one business day.')),panel('Unavailable',alertDemo('warning','Outside service hours','Leave a message and we will call tomorrow.')));
    case 'patterns/results': return four(panel('Query',`<input class="input" type="search" value="sleep" aria-label="Search">`),panel('Filtered',`<div class="stack"><span class="badge">Programs ×</span><span class="badge">2–5 nights ×</span><button class="btn ghost sm">Clear</button></div>`),panel('Results',`<div class="vstack">${basicCard('Sleep reset','4 nights · daily guidance')}</div>`),panel('Empty',`<div class="empty"><strong>No exact matches</strong><p>Clear one or more filters.</p><button class="btn secondary sm">Clear filters</button></div>`));
    case 'patterns/modal': return four(panel('Short form',`<button class="btn" data-open-modal>Open request</button>`),panel('Confirmation',`<button class="btn secondary" data-toast="Reservation updated">Confirm change</button>`),panel('Destructive',`<button class="btn danger" data-toast="Reservation cancelled">Cancel stay</button>`),panel('Error recovery',alertDemo('error','Could not save','Your entries are preserved. Try again.')));
    case 'blocks/hero': return four(panel('Destination',`<section class="site-hero"><div class="site-hero-content"><p class="eyebrow" style="color:var(--brand-300)">Mountain wellness retreat</p><h1>Space to recover.</h1><p>Considered stays and guided programs in a quiet alpine setting.</p>${bookingDemo()}</div></section>`),panel('Content hero',`<div class="vstack"><div class="breadcrumb">Home / Journal</div><h1 style="font-size:3rem">A practical guide to deeper rest</h1><p class="lede">Evidence-informed ideas for a calmer evening.</p></div>`),panel('Program hero',`<div class="split"><div><span class="badge">4–7 nights</span><h1 style="font-size:3.5rem">Rest & reset</h1><p>A personal program shaped around recovery.</p><button class="btn">Request a plan</button></div><div class="media">${image}</div></div>`),panel('Offer hero',`<div class="demo-panel" style="background:var(--pine-900);color:#fff"><span class="badge">Advance stay</span><h2>Save 20% on autumn dates.</h2><button class="btn">View dates</button></div>`));
    case 'blocks/task-wall': case 'blocks/card-collection': case 'blocks/related': return four(...[['Find a room','Compare space, view and flexibility.'],['Choose a program','Start with your intended outcome.'],['Plan transfers','Arrange a calm arrival.'],['Ask a host','Get practical guidance before booking.']].map(x=>panel(x[0],basicCard(x[0],x[1]))));
    case 'blocks/promo': return four(...[['Advance stay','Save 20% on selected autumn dates.'],['Longer retreat','Stay seven nights and receive a private session.'],['Weekday reset','Quieter dates with flexible arrival.'],['Member benefit','Early access to seasonal programs.']].map(x=>panel(x[0],`<span class="badge">Limited</span><h2>${x[0]}</h2><p>${x[1]}</p><button class="btn">View details</button>`)));
    case 'blocks/info-cta': return four(...[['Need help choosing?','Speak with a host'],['Traveling as a family?','Explore family stays'],['Planning recovery?','Request a consultation'],['Already booked?','Manage your stay']].map(x=>panel(x[0],`<div class="vstack"><h2>${x[0]}</h2><p>Get a clear next step without leaving the page context.</p><button class="btn">${x[1]}</button></div>`)));
    case 'blocks/quick-links': return four(...[['Frequent tasks',['Check dates','View programs','Get directions']],['Stay planning',['Transfers','Dining','Accessibility']],['Guest support',['Manage stay','Contact host','FAQ']],['Journal',['Sleep','Movement','Nutrition']]].map(x=>panel(x[0],`<div class="stack">${x[1].map(y=>`<a class="btn secondary sm" href="#">${y}</a>`).join('')}</div>`)));
    case 'blocks/article': return four(panel('Header',`<div class="breadcrumb">Home / Journal / Sleep</div><p class="eyebrow">Wellbeing · 6 min</p><h1 style="font-size:3rem">A calmer evening rhythm</h1>`),panel('Body',`<div class="prose"><p>Keep the reading measure between 60 and 75 characters. Use descriptive subheads and short paragraphs.</p><h2>Start with light</h2><p>Gradually lower brightness during the final hour of the day.</p></div>`),panel('Quote',`<blockquote class="quote">Small signals, repeated consistently, help the body anticipate rest.</blockquote>`),panel('End matter',`<div class="stack"><span class="badge">Sleep</span><span class="badge">Recovery</span><button class="btn secondary sm">Share article</button></div>`));
    case 'blocks/share': return four(...[['Copy link','⧉'],['Email','@'],['LinkedIn','in'],['Print','⌑']].map(x=>panel(x[0],`<button class="icon-btn" aria-label="${x[0]}" data-toast="${x[0]} selected">${x[1]}</button>`)));
    default:return four(panel('Default',basicCard()),panel('Compact',`<div class="vstack"><span class="badge">New</span><h2>Compact composition</h2><button class="btn sm">Action</button></div>`),panel('Dark ready',alertDemo('success','Theme aware','All colors inherit semantic tokens.')),panel('Responsive',`<p>This component adapts from wide desktop to 390 px without horizontal overflow.</p>`));
  }
}

function preview(content){return `<div class="preview-shell"><div class="preview-toolbar"><span class="label">Interactive preview</span><button class="tool-btn" data-preview-device="desktop" aria-label="Desktop preview" aria-pressed="true">${icons.desktop}</button><button class="tool-btn" data-preview-device="tablet" aria-label="Tablet preview">${icons.tablet}</button><button class="tool-btn" data-preview-device="mobile" aria-label="Mobile preview">${icons.mobile}</button><button class="tool-btn" data-preview-theme="light" aria-label="Light preview" aria-pressed="true">${icons.sun}</button><button class="tool-btn" data-preview-theme="dark" aria-label="Dark preview">${icons.moon}</button></div><div class="preview-stage" data-preview-theme="light"><div class="preview-frame" data-device="desktop">${content}</div></div></div>`}
function componentPage(path){const m=meta[path]||[titleFor(path),'Reusable interface element for premium service journeys.','component','semantic color and spacing tokens'];return `<div class="page"><header class="page-head"><div><p class="eyebrow">${groupFor(path)}</p><h1>${m[0]}</h1><p class="lede">${m[1]}</p></div><span class="badge">Stable</span></header>${preview(demoFor(path))}<section class="section-block"><div class="info-grid"><article class="info-card"><h3>Usage</h3><p>Choose the variant that matches hierarchy and content density. Keep labels specific and place the primary action last in keyboard order.</p></article><article class="info-card"><h3>Accessibility</h3><p>Use native elements, visible labels, a logical focus order and a 44 px minimum target. Never communicate state by color alone.</p></article><article class="info-card"><h3>API</h3><p><strong>Classes:</strong> ${m[2]}<br><strong>Tokens:</strong> ${m[3]}</p></article></div></section><section class="section-block"><h2>Accessible HTML</h2><pre class="code"><code>${escapeHTML(codeFor(path))}</code></pre></section></div>`}
function codeFor(path){if(path.includes('buttons'))return `<button class="btn" type="button">Check availability</button>`;if(path.includes('input'))return `<label class="field">Email\n  <input class="input" type="email" autocomplete="email">\n</label>`;if(path.includes('accordion'))return `<details>\n  <summary>What is included?</summary>\n  <p>Daily breakfast and mineral pool access.</p>\n</details>`;if(path.includes('tabs'))return `<div role="tablist" aria-label="Room details">\n  <button role="tab" aria-selected="true">Overview</button>\n</div>`;if(path.includes('modal'))return `<button aria-haspopup="dialog">Open request</button>\n<div role="dialog" aria-modal="true" aria-labelledby="dialog-title">…</div>`;return `<article class="card">\n  <h3>${titleFor(path)}</h3>\n  <p>Clear supporting content.</p>\n  <a href="#destination">Explore</a>\n</article>`}
function titleFor(path){for(const g of groups){const i=g.items.find(x=>x[1]===path);if(i)return i[0]}return 'Lumen'}
function groupFor(path){return groups.find(g=>g.items.some(i=>i[1]===path))?.name||'Design system'}

function foundationsPage(path){
  const common=`<header class="page-head"><div><p class="eyebrow">Foundations</p><h1>${titleFor(path)}</h1><p class="lede">A semantic foundation derived from the audited structure, rebuilt for an anonymous enterprise wellness brand.</p></div><span class="badge">v1.0</span></header>`;
  if(path==='foundations/color')return `<div class="page">${common}${preview(four(...[['Surface','var(--surface)'],['Text','var(--text)'],['Accent','var(--accent)'],['Success','var(--success)']].map(x=>panel(x[0],`<div class="swatch" style="background:${x[1]}"></div><div class="token"><span>${x[0]}</span><code>${x[1]}</code></div>`))))}<section class="section-block"><h2>Semantic roles</h2><p class="lede">Components use roles such as surface, text, muted, border, accent and status. Light, dark and system themes redefine roles centrally.</p></section></div>`;
  if(path==='foundations/typography')return `<div class="page">${common}${preview(four(panel('Display',`<div style="font:500 3rem/1 var(--display)">Rest with intention.</div>`),panel('Heading',`<h2>Designed for clear decisions</h2>`),panel('Body',`<p>Body text starts at 16 px with a 1.6 line height and comfortable measure.</p>`),panel('Metadata',`<div class="eyebrow">Program · 4 nights</div>`)))}</div>`;
  if(path==='foundations/layout')return `<div class="page">${common}${preview(four(...[['4 px','0.25rem'],['16 px','1rem'],['32 px','2rem'],['64 px','4rem']].map(x=>panel(x[0],`<div style="height:1.5rem;width:${x[1]};background:var(--accent)"></div><p>${x[1]}</p>`))))}<section class="section-block"><h2>Grid & breakpoints</h2><div class="info-grid"><div class="info-card"><h3>Content</h3><p>76rem maximum, fluid outer gutters.</p></div><div class="info-card"><h3>Reading</h3><p>46rem maximum for sustained prose.</p></div><div class="info-card"><h3>Breakpoints</h3><p>390, 768, 1024 and 1440 px.</p></div></div></section></div>`;
  if(path==='foundations/shape')return `<div class="page">${common}${preview(four(...[['Small','.25rem'],['Medium','.5rem'],['Large','1rem'],['Pill','999px']].map((x,i)=>panel(x[0],`<div style="height:6rem;border-radius:${x[1]};background:var(--surface-2);box-shadow:var(--shadow-${i<1?'sm':i<3?'md':'lg'})"></div><p>${x[1]}</p>`))))}</div>`;
  if(path==='foundations/media')return `<div class="page">${common}${preview(four(panel('Photography',`<div class="media">${image}</div>`),panel('Landscape crop',`<div class="media" style="aspect-ratio:3/2">${image}</div>`),panel('Square crop',`<div class="media" style="aspect-ratio:1">${image}</div>`),panel('Icon rule',`<div class="stack"><button class="icon-btn" aria-label="Search">${icons.search}</button><p>Use simple stroke-like symbols with text alternatives.</p></div>`)))}<section class="section-block"><p class="lede">Use owned or properly licensed imagery, meaningful alt text and fixed aspect ratios to prevent layout shift.</p></section></div>`;
  if(path==='foundations/motion')return `<div class="page">${common}${preview(four(panel('Fast','120 ms — press feedback'),panel('Base','220 ms — panels and controls'),panel('Slow','420 ms — page-level reveal'),panel('Reduced motion','Transitions collapse to 0.01 ms when requested')))}<section class="section-block"><p class="lede">Motion clarifies cause and effect. It never blocks content, loops without purpose or ignores reduced-motion preferences.</p></section></div>`;
  return overviewPage();
}

function overviewPage(){const count=groups.reduce((n,g)=>n+g.items.length,0);return `<div class="page"><header class="page-head"><div><p class="eyebrow">Lumen enterprise system</p><h1>Calm structure for complex service journeys.</h1><p class="lede">A brand-neutral design system for premium hospitality and wellness—built from audited patterns, not copied assets.</p></div><span class="badge">${count} documented routes</span></header><div class="info-grid"><article class="info-card"><h3>Start with tokens</h3><p>Semantic roles support light, dark and system themes across the catalog and examples.</p><a href="#/foundations/color">Explore color ${icons.arrow}</a></article><article class="info-card"><h3>Compose components</h3><p>Accessible primitives cover actions, forms, navigation, feedback and content.</p><a href="#/actions/buttons">Browse components ${icons.arrow}</a></article><article class="info-card"><h3>See complete pages</h3><p>Responsive destination, rooms and program pages demonstrate the system in context.</p><a href="#/examples/home">Open examples ${icons.arrow}</a></article></div><section class="section-block"><h2>Audited characteristics</h2>${preview(four(panel('Editorial hierarchy','Serif display headings paired with a neutral sans-serif body.'),panel('Service navigation','A restrained header, deep menus and a persistent reservation action.'),panel('Commercial clarity','Availability controls, comparison tables and card collections.'),panel('Responsive behavior','Desktop navigation becomes compact at tablet; all grids collapse by 390 px.')))}</section></div>`}

function siteHome(){return `<div class="page" style="max-width:none;padding-left:0;padding-right:0;padding-top:0"><div class="site-example">${headerDemo()}<section class="site-hero"><div class="site-hero-content"><p class="eyebrow" style="color:var(--brand-300)">Mountain wellness retreat</p><h1>Space to recover.</h1><p>Considered stays, mineral bathing and guided programs in a quiet alpine setting.</p>${bookingDemo()}</div></section><section class="site-section"><div class="section-heading"><div><p class="eyebrow">Choose your path</p><h2>Begin with what you need.</h2></div><p class="lede">Stay for quiet, follow a guided program or build a restorative week with a host.</p></div><div class="card-grid">${basicCard('Restful stays','Rooms designed around light, quiet and landscape.')}${basicCard('Guided programs','Focused plans for sleep, movement and recovery.')}${basicCard('Mineral bathing','Daily access to warm water and mountain air.')}</div></section><section class="site-section alt"><div class="split"><div class="media" style="aspect-ratio:4/5">${image}</div><div><p class="eyebrow">A measured approach</p><h2>Care that adapts to real life.</h2><p>Each stay begins with a short conversation. Choose as much structure as you need, keep the rest of your days open.</p><blockquote class="quote">Rest is not an escape from the day. It is part of how the day works.</blockquote><button class="btn">Explore our approach</button></div></div></section><section class="site-section"><div class="section-heading"><h2>Proof in the details.</h2></div><div class="card-grid"><div class="metric"><strong>24</strong><span>private rooms</span></div><div class="metric"><strong>14</strong><span>guided practices</span></div><div class="metric"><strong>4.9</strong><span>guest rating</span></div></div></section>${footerDemo()}</div></div>`}
function siteRooms(){return `<div class="page" style="max-width:none;padding-left:0;padding-right:0;padding-top:0"><div class="site-example">${headerDemo()}<section class="site-section alt"><nav class="breadcrumb">Home / Stays</nav><p class="eyebrow">Rooms & suites</p><h1 style="font-size:clamp(3rem,7vw,6rem)">Stay close to quiet.</h1><p class="lede">Every room prioritizes natural light, acoustic comfort and uncluttered space.</p></section><section class="site-section"><div style="overflow:auto"><table class="price-table"><thead><tr><th>Room</th><th>Area</th><th>Guests</th><th>View</th><th>From</th></tr></thead><tbody><tr><td>Forest room</td><td>28 m²</td><td>2</td><td>Pine</td><td>$240</td></tr><tr><td>Ridge suite</td><td>42 m²</td><td>3</td><td>Valley</td><td>$360</td></tr><tr><td>Terrace residence</td><td>68 m²</td><td>4</td><td>Mountain</td><td>$520</td></tr></tbody></table></div><div class="section-heading" style="margin-top:4rem"><h2>Find your space.</h2><button class="btn secondary">Compare selected</button></div><div class="card-grid">${basicCard('Forest room','28 m² · king bed · pine view')}${basicCard('Ridge suite','42 m² · living area · valley view')}${basicCard('Terrace residence','68 m² · private terrace · mountain view')}</div></section>${footerDemo()}</div></div>`}
function siteProgram(){return `<div class="page" style="max-width:none;padding-left:0;padding-right:0;padding-top:0"><div class="site-example">${headerDemo()}<section class="site-section"><nav class="breadcrumb">Home / Programs / Rest & reset</nav><div class="split" style="margin-top:2rem"><div><span class="badge">4–7 nights</span><p class="eyebrow" style="margin-top:1rem">Guided program</p><h1 style="font-size:clamp(3rem,7vw,6rem)">Rest & reset.</h1><p class="lede">A flexible recovery plan for guests who need better sleep, a steadier rhythm and room to think.</p><div class="stack" style="margin-top:1.5rem"><button class="btn">Request a plan</button><button class="btn secondary">View inclusions</button></div></div><div class="media" style="aspect-ratio:4/5">${image}</div></div></section><section class="site-section alt"><div class="section-heading"><h2>A clear, unhurried structure.</h2><p class="lede">The program adjusts after your arrival consultation.</p></div><div class="card-grid"><div class="info-card"><span class="badge">Day 1</span><h3>Understand</h3><p>Arrival, consultation and a simple recovery baseline.</p></div><div class="info-card"><span class="badge">Days 2–4</span><h3>Restore</h3><p>Movement, mineral bathing and quiet guided practice.</p></div><div class="info-card"><span class="badge">Final day</span><h3>Continue</h3><p>A realistic plan to carry the useful parts home.</p></div></div></section><section class="site-section"><div class="split"><div><h2>What is included</h2>${accordionDemo()}</div><div class="demo-panel"><p class="eyebrow">From $1,480</p><h2>Plan your stay</h2><p>Tell us your dates and a host will suggest the most suitable format.</p>${field('Email','you@example.com','email')}<button class="btn" style="margin-top:1rem">Request details</button></div></div></section>${footerDemo()}</div></div>`}

function layout(content,path){return `<div class="app-shell"><header class="topbar"><button class="icon-btn square mobile-menu" id="menu-toggle" aria-label="Open navigation" aria-expanded="false">${icons.menu}</button><a class="brand" href="#/overview"><span class="brand-mark">L</span><span>Lumen<small>Design system</small></span></a><div class="top-actions"><div class="theme-switch" aria-label="Theme"><button data-theme="light" aria-label="Light theme">${icons.sun}</button><button data-theme="dark" aria-label="Dark theme">${icons.moon}</button><button data-theme="system" aria-label="System theme">${icons.system}</button></div></div></header><aside class="sidebar" id="sidebar" aria-label="Catalog navigation">${groups.map(g=>`<div class="sidebar-group"><div class="sidebar-label">${g.name}</div>${g.items.map(i=>`<a class="nav-link ${path===i[1]?'active':''}" href="#/${i[1]}"><span class="nav-dot"></span>${i[0]}</a>`).join('')}</div>`).join('')}</aside><main class="main" id="main" tabindex="-1">${content}</main></div><div class="modal-backdrop" id="demo-modal" hidden><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="icon-btn" style="float:right" data-close-modal aria-label="Close dialog">${icons.close}</button><p class="eyebrow">Booking note</p><h2 id="modal-title">Anything we should know?</h2><p class="lede">Share arrival or accessibility details. You can update this later.</p><textarea class="textarea" aria-label="Booking note"></textarea><div class="modal-actions"><button class="btn secondary" data-close-modal>Cancel</button><button class="btn" data-close-modal data-toast="Note saved">Save note</button></div></section></div>`}

function render(){const path=(location.hash.replace(/^#\/?/,'')||'overview').split('?')[0];let content;if(path==='overview')content=overviewPage();else if(path.startsWith('foundations/'))content=foundationsPage(path);else if(path==='examples/home')content=siteHome();else if(path==='examples/rooms')content=siteRooms();else if(path==='examples/program')content=siteProgram();else content=componentPage(path);document.getElementById('app').innerHTML=layout(content,path);document.title=`${titleFor(path)} · Lumen Design System`;bind();window.scrollTo(0,0)}
function bind(){
  document.querySelectorAll('[data-theme]').forEach(b=>{const saved=localStorage.getItem('lumen-theme')||'light';b.setAttribute('aria-pressed',String(b.dataset.theme===saved));b.onclick=()=>{document.documentElement.dataset.theme=b.dataset.theme;localStorage.setItem('lumen-theme',b.dataset.theme);document.querySelectorAll('[data-theme]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}});
  const menu=document.getElementById('menu-toggle'),side=document.getElementById('sidebar');if(menu)menu.onclick=()=>{const open=side.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?icons.close:icons.menu};
  document.querySelectorAll('.nav-link').forEach(a=>a.onclick=()=>side?.classList.remove('open'));
  document.querySelectorAll('[data-preview-device]').forEach(b=>b.onclick=()=>{const shell=b.closest('.preview-shell');shell.querySelector('.preview-frame').dataset.device=b.dataset.previewDevice;shell.querySelectorAll('[data-preview-device]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
  document.querySelectorAll('[data-preview-theme]').forEach(b=>b.onclick=()=>{const shell=b.closest('.preview-shell');shell.querySelector('.preview-stage').dataset.previewTheme=b.dataset.previewTheme;shell.querySelectorAll('[data-preview-theme]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
  const modal=document.getElementById('demo-modal');document.querySelectorAll('[data-open-modal]').forEach(b=>b.onclick=()=>{modal.hidden=false;modal.querySelector('textarea').focus()});document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>{modal.hidden=true});if(modal)modal.onclick=e=>{if(e.target===modal)modal.hidden=true};
  document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));
  document.querySelectorAll('[data-demo-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();toast('Demo submitted successfully')});
  document.querySelectorAll('[data-tabs]').forEach(t=>{t.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{t.querySelectorAll('.tab').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');t.querySelector('.tab-panel').textContent={overview:'A considered stay with quiet mountain views.',details:'King bed, mineral bath access and breakfast included.',policy:'Flexible changes up to 48 hours before arrival.'}[b.dataset.tab]})});
}
function toast(message){const r=document.getElementById('toast-region'),n=document.createElement('div');n.className='toast';n.setAttribute('role','status');n.textContent=message;r.appendChild(n);setTimeout(()=>n.remove(),3200)}
document.documentElement.dataset.theme=localStorage.getItem('lumen-theme')||'light';window.addEventListener('hashchange',render);render();
